// Code generated by protoc-gen-go. DO NOT EDIT.
// source: emp/emp.proto

package emp

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type EmployeeRequest struct {
	EmpID                int32                      `protobuf:"varint,1,opt,name=empID,proto3" json:"empID,omitempty"`
	Name                 string                     `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Email                string                     `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Addresses            []*EmployeeRequest_Address `protobuf:"bytes,4,rep,name=addresses,proto3" json:"addresses,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *EmployeeRequest) Reset()         { *m = EmployeeRequest{} }
func (m *EmployeeRequest) String() string { return proto.CompactTextString(m) }
func (*EmployeeRequest) ProtoMessage()    {}
func (*EmployeeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ca965c0895299ad6, []int{0}
}

func (m *EmployeeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EmployeeRequest.Unmarshal(m, b)
}
func (m *EmployeeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EmployeeRequest.Marshal(b, m, deterministic)
}
func (m *EmployeeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EmployeeRequest.Merge(m, src)
}
func (m *EmployeeRequest) XXX_Size() int {
	return xxx_messageInfo_EmployeeRequest.Size(m)
}
func (m *EmployeeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_EmployeeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_EmployeeRequest proto.InternalMessageInfo

func (m *EmployeeRequest) GetEmpID() int32 {
	if m != nil {
		return m.EmpID
	}
	return 0
}

func (m *EmployeeRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *EmployeeRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *EmployeeRequest) GetAddresses() []*EmployeeRequest_Address {
	if m != nil {
		return m.Addresses
	}
	return nil
}

type EmployeeRequest_Address struct {
	Street               string   `protobuf:"bytes,1,opt,name=street,proto3" json:"street,omitempty"`
	City                 string   `protobuf:"bytes,2,opt,name=city,proto3" json:"city,omitempty"`
	State                string   `protobuf:"bytes,3,opt,name=state,proto3" json:"state,omitempty"`
	Zip                  string   `protobuf:"bytes,4,opt,name=zip,proto3" json:"zip,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EmployeeRequest_Address) Reset()         { *m = EmployeeRequest_Address{} }
func (m *EmployeeRequest_Address) String() string { return proto.CompactTextString(m) }
func (*EmployeeRequest_Address) ProtoMessage()    {}
func (*EmployeeRequest_Address) Descriptor() ([]byte, []int) {
	return fileDescriptor_ca965c0895299ad6, []int{0, 0}
}

func (m *EmployeeRequest_Address) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EmployeeRequest_Address.Unmarshal(m, b)
}
func (m *EmployeeRequest_Address) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EmployeeRequest_Address.Marshal(b, m, deterministic)
}
func (m *EmployeeRequest_Address) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EmployeeRequest_Address.Merge(m, src)
}
func (m *EmployeeRequest_Address) XXX_Size() int {
	return xxx_messageInfo_EmployeeRequest_Address.Size(m)
}
func (m *EmployeeRequest_Address) XXX_DiscardUnknown() {
	xxx_messageInfo_EmployeeRequest_Address.DiscardUnknown(m)
}

var xxx_messageInfo_EmployeeRequest_Address proto.InternalMessageInfo

func (m *EmployeeRequest_Address) GetStreet() string {
	if m != nil {
		return m.Street
	}
	return ""
}

func (m *EmployeeRequest_Address) GetCity() string {
	if m != nil {
		return m.City
	}
	return ""
}

func (m *EmployeeRequest_Address) GetState() string {
	if m != nil {
		return m.State
	}
	return ""
}

func (m *EmployeeRequest_Address) GetZip() string {
	if m != nil {
		return m.Zip
	}
	return ""
}

type EmployeeResponse struct {
	EmpId                int32    `protobuf:"varint,1,opt,name=empId,proto3" json:"empId,omitempty"`
	Success              bool     `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EmployeeResponse) Reset()         { *m = EmployeeResponse{} }
func (m *EmployeeResponse) String() string { return proto.CompactTextString(m) }
func (*EmployeeResponse) ProtoMessage()    {}
func (*EmployeeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ca965c0895299ad6, []int{1}
}

func (m *EmployeeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EmployeeResponse.Unmarshal(m, b)
}
func (m *EmployeeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EmployeeResponse.Marshal(b, m, deterministic)
}
func (m *EmployeeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EmployeeResponse.Merge(m, src)
}
func (m *EmployeeResponse) XXX_Size() int {
	return xxx_messageInfo_EmployeeResponse.Size(m)
}
func (m *EmployeeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_EmployeeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_EmployeeResponse proto.InternalMessageInfo

func (m *EmployeeResponse) GetEmpId() int32 {
	if m != nil {
		return m.EmpId
	}
	return 0
}

func (m *EmployeeResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

type SingleEmployeeRequest struct {
	EmpId                int32    `protobuf:"varint,1,opt,name=empId,proto3" json:"empId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SingleEmployeeRequest) Reset()         { *m = SingleEmployeeRequest{} }
func (m *SingleEmployeeRequest) String() string { return proto.CompactTextString(m) }
func (*SingleEmployeeRequest) ProtoMessage()    {}
func (*SingleEmployeeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ca965c0895299ad6, []int{2}
}

func (m *SingleEmployeeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SingleEmployeeRequest.Unmarshal(m, b)
}
func (m *SingleEmployeeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SingleEmployeeRequest.Marshal(b, m, deterministic)
}
func (m *SingleEmployeeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SingleEmployeeRequest.Merge(m, src)
}
func (m *SingleEmployeeRequest) XXX_Size() int {
	return xxx_messageInfo_SingleEmployeeRequest.Size(m)
}
func (m *SingleEmployeeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SingleEmployeeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SingleEmployeeRequest proto.InternalMessageInfo

func (m *SingleEmployeeRequest) GetEmpId() int32 {
	if m != nil {
		return m.EmpId
	}
	return 0
}

type EmployeeFilter struct {
	Keyword              string   `protobuf:"bytes,1,opt,name=keyword,proto3" json:"keyword,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EmployeeFilter) Reset()         { *m = EmployeeFilter{} }
func (m *EmployeeFilter) String() string { return proto.CompactTextString(m) }
func (*EmployeeFilter) ProtoMessage()    {}
func (*EmployeeFilter) Descriptor() ([]byte, []int) {
	return fileDescriptor_ca965c0895299ad6, []int{3}
}

func (m *EmployeeFilter) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EmployeeFilter.Unmarshal(m, b)
}
func (m *EmployeeFilter) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EmployeeFilter.Marshal(b, m, deterministic)
}
func (m *EmployeeFilter) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EmployeeFilter.Merge(m, src)
}
func (m *EmployeeFilter) XXX_Size() int {
	return xxx_messageInfo_EmployeeFilter.Size(m)
}
func (m *EmployeeFilter) XXX_DiscardUnknown() {
	xxx_messageInfo_EmployeeFilter.DiscardUnknown(m)
}

var xxx_messageInfo_EmployeeFilter proto.InternalMessageInfo

func (m *EmployeeFilter) GetKeyword() string {
	if m != nil {
		return m.Keyword
	}
	return ""
}

func init() {
	proto.RegisterType((*EmployeeRequest)(nil), "emp.EmployeeRequest")
	proto.RegisterType((*EmployeeRequest_Address)(nil), "emp.EmployeeRequest.Address")
	proto.RegisterType((*EmployeeResponse)(nil), "emp.EmployeeResponse")
	proto.RegisterType((*SingleEmployeeRequest)(nil), "emp.SingleEmployeeRequest")
	proto.RegisterType((*EmployeeFilter)(nil), "emp.EmployeeFilter")
}

func init() { proto.RegisterFile("emp/emp.proto", fileDescriptor_ca965c0895299ad6) }

var fileDescriptor_ca965c0895299ad6 = []byte{
	// 336 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x92, 0xcf, 0x4e, 0x32, 0x31,
	0x14, 0xc5, 0x19, 0x86, 0xbf, 0x97, 0x7c, 0x7c, 0xa4, 0x01, 0x33, 0x99, 0xb8, 0x20, 0x5d, 0x11,
	0x13, 0x31, 0xc1, 0x9d, 0x1b, 0x83, 0x01, 0x8d, 0xdb, 0x1a, 0x97, 0x2e, 0xc6, 0xe9, 0x8d, 0x99,
	0x38, 0x65, 0x6a, 0x5b, 0x62, 0xf0, 0x41, 0x7c, 0x4a, 0x1f, 0xc2, 0xb4, 0x43, 0x01, 0x09, 0xb8,
	0x71, 0x77, 0xcf, 0xcd, 0x99, 0x73, 0x7f, 0xa7, 0x19, 0xf8, 0x87, 0x42, 0x5e, 0xa0, 0x90, 0x63,
	0xa9, 0x0a, 0x53, 0x90, 0x10, 0x85, 0xa4, 0x5f, 0x01, 0xfc, 0x9f, 0x0b, 0x99, 0x17, 0x2b, 0x44,
	0x86, 0x6f, 0x4b, 0xd4, 0x86, 0xf4, 0xa1, 0x8e, 0x42, 0xde, 0xcf, 0xa2, 0x60, 0x18, 0x8c, 0xea,
	0xac, 0x14, 0x84, 0x40, 0x6d, 0x91, 0x08, 0x8c, 0xaa, 0xc3, 0x60, 0xd4, 0x66, 0x6e, 0x2e, 0x9d,
	0x49, 0x96, 0x47, 0xa1, 0x5b, 0x96, 0x82, 0x5c, 0x41, 0x3b, 0xe1, 0x5c, 0xa1, 0xd6, 0xa8, 0xa3,
	0xda, 0x30, 0x1c, 0x75, 0x26, 0xa7, 0x63, 0x7b, 0x77, 0xef, 0xd0, 0x78, 0x5a, 0xba, 0xd8, 0xd6,
	0x1e, 0x3f, 0x41, 0x73, 0xbd, 0x25, 0x27, 0xd0, 0xd0, 0x46, 0x21, 0x1a, 0xc7, 0xd1, 0x66, 0x6b,
	0x65, 0x41, 0xd2, 0xcc, 0xac, 0x3c, 0x88, 0x9d, 0x2d, 0x88, 0x36, 0x89, 0x41, 0x0f, 0xe2, 0x04,
	0xe9, 0x41, 0xf8, 0x91, 0xc9, 0xa8, 0xe6, 0x76, 0x76, 0xa4, 0x37, 0xd0, 0xdb, 0x42, 0x68, 0x59,
	0x2c, 0x34, 0xfa, 0xba, 0x7c, 0xb7, 0x2e, 0x27, 0x11, 0x34, 0xf5, 0x32, 0x4d, 0x51, 0x6b, 0x77,
	0xa8, 0xc5, 0xbc, 0xa4, 0xe7, 0x30, 0x78, 0xc8, 0x16, 0x2f, 0x39, 0x1e, 0x79, 0xb7, 0x9f, 0x41,
	0xf4, 0x0c, 0xba, 0xde, 0x78, 0x9b, 0xe5, 0x06, 0x95, 0x8d, 0x7e, 0xc5, 0xd5, 0x7b, 0xa1, 0xf8,
	0xba, 0x99, 0x97, 0x93, 0xcf, 0x2a, 0xb4, 0xbc, 0x99, 0x5c, 0x43, 0x37, 0x55, 0x98, 0x98, 0xcd,
	0x1d, 0xd2, 0x3f, 0xf4, 0x8a, 0xf1, 0x60, 0x6f, 0x5b, 0xd6, 0xa2, 0x15, 0x32, 0x85, 0xce, 0x1d,
	0x9a, 0xcd, 0xd7, 0xb1, 0xf3, 0x1d, 0x44, 0x8f, 0x0f, 0x26, 0xd3, 0x8a, 0x65, 0x78, 0x94, 0xfc,
	0x0f, 0x0c, 0x73, 0xe8, 0xce, 0x30, 0xc7, 0x9d, 0x80, 0xdf, 0x30, 0x8e, 0xc5, 0x3c, 0x37, 0xdc,
	0x2f, 0x7b, 0xf9, 0x1d, 0x00, 0x00, 0xff, 0xff, 0x5f, 0x69, 0xf1, 0x4f, 0xc3, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// EmployeeClient is the client API for Employee service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type EmployeeClient interface {
	//Create a new Employee Record.
	CreateEmployee(ctx context.Context, in *EmployeeRequest, opts ...grpc.CallOption) (*EmployeeResponse, error)
	// Get the emplyee using uniq employee Id.
	GetEmployee(ctx context.Context, in *SingleEmployeeRequest, opts ...grpc.CallOption) (*EmployeeRequest, error)
	// Delete Employee Record
	UpdateEmployee(ctx context.Context, in *EmployeeRequest, opts ...grpc.CallOption) (*EmployeeResponse, error)
	// Delete Employee Record
	DeleteEmployee(ctx context.Context, in *SingleEmployeeRequest, opts ...grpc.CallOption) (*EmployeeResponse, error)
}

type employeeClient struct {
	cc *grpc.ClientConn
}

func NewEmployeeClient(cc *grpc.ClientConn) EmployeeClient {
	return &employeeClient{cc}
}

func (c *employeeClient) CreateEmployee(ctx context.Context, in *EmployeeRequest, opts ...grpc.CallOption) (*EmployeeResponse, error) {
	out := new(EmployeeResponse)
	err := c.cc.Invoke(ctx, "/emp.Employee/createEmployee", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *employeeClient) GetEmployee(ctx context.Context, in *SingleEmployeeRequest, opts ...grpc.CallOption) (*EmployeeRequest, error) {
	out := new(EmployeeRequest)
	err := c.cc.Invoke(ctx, "/emp.Employee/GetEmployee", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *employeeClient) UpdateEmployee(ctx context.Context, in *EmployeeRequest, opts ...grpc.CallOption) (*EmployeeResponse, error) {
	out := new(EmployeeResponse)
	err := c.cc.Invoke(ctx, "/emp.Employee/UpdateEmployee", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *employeeClient) DeleteEmployee(ctx context.Context, in *SingleEmployeeRequest, opts ...grpc.CallOption) (*EmployeeResponse, error) {
	out := new(EmployeeResponse)
	err := c.cc.Invoke(ctx, "/emp.Employee/DeleteEmployee", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EmployeeServer is the server API for Employee service.
type EmployeeServer interface {
	//Create a new Employee Record.
	CreateEmployee(context.Context, *EmployeeRequest) (*EmployeeResponse, error)
	// Get the emplyee using uniq employee Id.
	GetEmployee(context.Context, *SingleEmployeeRequest) (*EmployeeRequest, error)
	// Delete Employee Record
	UpdateEmployee(context.Context, *EmployeeRequest) (*EmployeeResponse, error)
	// Delete Employee Record
	DeleteEmployee(context.Context, *SingleEmployeeRequest) (*EmployeeResponse, error)
}

func RegisterEmployeeServer(s *grpc.Server, srv EmployeeServer) {
	s.RegisterService(&_Employee_serviceDesc, srv)
}

func _Employee_CreateEmployee_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmployeeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmployeeServer).CreateEmployee(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/emp.Employee/CreateEmployee",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmployeeServer).CreateEmployee(ctx, req.(*EmployeeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Employee_GetEmployee_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SingleEmployeeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmployeeServer).GetEmployee(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/emp.Employee/GetEmployee",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmployeeServer).GetEmployee(ctx, req.(*SingleEmployeeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Employee_UpdateEmployee_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmployeeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmployeeServer).UpdateEmployee(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/emp.Employee/UpdateEmployee",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmployeeServer).UpdateEmployee(ctx, req.(*EmployeeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Employee_DeleteEmployee_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SingleEmployeeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmployeeServer).DeleteEmployee(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/emp.Employee/DeleteEmployee",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmployeeServer).DeleteEmployee(ctx, req.(*SingleEmployeeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Employee_serviceDesc = grpc.ServiceDesc{
	ServiceName: "emp.Employee",
	HandlerType: (*EmployeeServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "createEmployee",
			Handler:    _Employee_CreateEmployee_Handler,
		},
		{
			MethodName: "GetEmployee",
			Handler:    _Employee_GetEmployee_Handler,
		},
		{
			MethodName: "UpdateEmployee",
			Handler:    _Employee_UpdateEmployee_Handler,
		},
		{
			MethodName: "DeleteEmployee",
			Handler:    _Employee_DeleteEmployee_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "emp/emp.proto",
}
